<!-- Sub2Tech Basket Tracking -->
<script>
    var basketXmlCookieName = '<?= /* @NoEscape */ \Space48\SubTech\Observer\SalesQuoteSaveAfterObserver::BASKET_XML_COOKIE_NAME ?>';

    require([
        'Space48_GtmDataLayer/js/tracking'
    ], function(tracking){

        var basketXml = tracking.getCookie(basketXmlCookieName);

        if (basketXml !== null) {

            basketXml = decodeURIComponent(basketXml.replace(/\+/g, ' '));
            __s2tQ.push(['sendBasket' , basketXml]);
            tracking.delCookie(basketXmlCookieName);
        }
    });

</script>
<!-- Sub2Tech Basket Tracking -->