<!-- Sub2Tech Basket Tracking -->
<script>
    var basketXmlCookieName = '<?= /* @NoEscape */ \Space48\SubTech\Observer\SalesQuoteSaveAfterObserver::BASKET_XML_COOKIE_NAME ?>';

    require([
        'Space48_SubTech/js/cookies'
    ], function(cookies){

        var basketXml = cookies.getCookie(basketXmlCookieName);

        if (basketXml !== null) {

            basketXml = decodeURIComponent(basketXml.replace(/\+/g, ' '));
            __s2tQ.push(['sendBasket' , basketXml]);
            cookies.delCookie(basketXmlCookieName);
        }
    });

</script>
<!-- Sub2Tech Basket Tracking -->