<!-- Sub2Tech Customer Tracking -->
<script>
    var customerDataCookieName = '<?= /* @NoEscape */ \Space48\SubTech\Observer\CustomerLoginSuccessObserver::CUSTOMER_DATA_COOKIE_NAME ?>';

    require([
        'Space48_GtmDataLayer/js/tracking'
    ], function(tracking){

        var customerData = tracking.getCookie(customerDataCookieName);

        if (customerData !== null) {
            customerData = tracking.parseJson(customerData);
            __s2tQ.push(['storeData' , customerData]);
            tracking.delCookie(customerDataCookieName);
        }
    });

</script>
<!-- Sub2Tech Customer Tracking -->