<!-- Sub2Tech Customer Tracking -->
<script>
    var customerDataCookieName = '<?= /* @NoEscape */ \Space48\SubTech\Observer\CustomerLoginSuccessObserver::CUSTOMER_DATA_COOKIE_NAME ?>';

    require([
        'Space48_SubTech/js/cookies'
    ], function(cookies){

        var customerData = cookies.getCookie(customerDataCookieName);

        if (customerData !== null) {
            customerData = cookies.parseJson(customerData);
            __s2tQ.push(['storeData' , customerData]);
            cookies.delCookie(customerDataCookieName);
        }
    });

</script>
<!-- Sub2Tech Customer Tracking -->