<!-- Sub2Tech Subscriber Tracking -->
<script>
    require([
        'Space48_GtmDataLayer/js/tracking'
    ], function(tracking){

        var email = tracking.getCookie("subscriberEmail");

        if (email !== null) {
            email = tracking.parseJson(email);
            __s2tQ.push(['storeData', email]);
            tracking.delCookie("subscriberEmail");
        }
    });
</script>
<!-- Sub2Tech Subscriber Tracking -->